name: reinforced_interfuser
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pip:
      - -r scenario_runner/requirements.txt
      - -r gym_environment/requirements.txt
      - -r train_RL/requirements.txt
      - -r train_encoder/requirements.txt
      - -r data_gen/requirements.txt
      - -r benchmark/requirements.txt
      - mmsegmentation==0.25.0
      - mmdet==2.25.0
